version: '3.8'

services:
  api:
    build: ./api
    command: npm start
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - HOST=http://realworld-docker.com
